config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", :sessions => "sessions"}
  resources :users
  resources :tables
  resources :friendships
  root 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/howtoplay', to: 'static_pages#how_to_play', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end

  def howtoplay
  end

  def about
  end

  def contact
  end
end

app/views/static_pages/about.html.erb
<%provide(:title, 'About')%>
<h1>About</h1>
<p>This is not about you or me. This is about us.</p>

app/views/static_pages/contact.html.erb
<%provide(:title, 'Contact')%>
<h1>Contact</h1>
<p>Find me in school. Probably eating at a canteen.</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="center hero-unit">
<h1>Welcome to FindTheMafia</h1>
  <% if user_signed_in? %>
  Logged in as <p><%= current_user.email %></p>
  <%= link_to "Your Profile", current_user, class: "btn btn-large btn-primary"%>
  <%= link_to "Create A Table", new_table_path, class: "btn btn-large btn-primary"%>
  <%= link_to "Join A Table", tables_path, class: "btn btn-large btn-primary"%>
  <%else%>
  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
  <%end%>
    
  </div>

app/views/static_pages/how_to_play.html.erb
<%provide(:title, 'How To Play')%>
<h1>How To Play FTM/Werewolf</h1>
<p>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ante lectus, vestibulum id nibh id, commodo sagittis nunc. Praesent dapibus eros nec dui vestibulum euismod. Aenean quis velit lacus. Donec suscipit dolor vitae efficitur efficitur. Integer orci ligula, mollis nec lacus sit amet, vestibulum consequat urna. Vestibulum rutrum sagittis turpis, vel facilisis lacus imperdiet vel. Phasellus eros elit, pellentesque eleifend neque eget, commodo ultrices dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas malesuada viverra turpis vel elementum. Nulla non justo pretium, porta ex vel, vehicula libero. Morbi dignissim, ipsum vitae placerat interdum, arcu eros ultricies mi, sit amet viverra mauris orci eu mi. Duis nibh ante, congue rhoncus orci ac, vehicula sodales arcu. Sed convallis gravida nulla et lacinia. Integer vel lacus a justo laoreet mollis sit amet a purus. Nunc pharetra tellus vitae dui rutrum, ut lacinia purus maximus. </p>
<div>
  <p>
Pellentesque in eros ut lacus facilisis mollis. Duis aliquet, justo eu tempor ultricies, odio diam suscipit ipsum, facilisis imperdiet justo enim quis elit. Suspendisse ultrices, nunc commodo dapibus feugiat, arcu quam varius dolor, nec consequat orci ligula sit amet orci. Etiam sit amet ipsum interdum, posuere nisi non, egestas libero. Cras lacinia tincidunt varius. Nullam tellus massa, bibendum vitae congue id, suscipit nec mi. Quisque velit nisi, aliquam vel convallis accumsan, vestibulum in velit. In convallis lacinia massa sed pretium. Pellentesque mi mi, rutrum nec nisi vel, tincidunt placerat velit. Nulla mollis ipsum mi. Pellentesque sit amet tellus viverra, tincidunt ipsum quis, congue metus. Nunc aliquet mi ac sapien aliquam, ac mollis libero rutrum. Aenean et ipsum vitae felis sollicitudin tristique eu id justo. Maecenas lacinia turpis eu diam finibus scelerisque. Ut in odio diam. </p>