config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", :sessions => "sessions"}
  resources :users
  resources :tables
  resources :friendships
  root 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/howtoplay', to: 'static_pages#how_to_play', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  belongs_to :table
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
  :omniauthable, :omniauth_providers => [:facebook]
  validates :nickname, presence: true, uniqueness: true
  validates :exptolvl, numericality: {only_integer: true}
  validates :lvl, numericality: {only_integer: true}
  validates :exp, numericality: {only_integer: true}
  validates :status, presence: true

 # def self.from_omniauth(auth)
    #  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
     #   user.provider = auth.provider
    #   user.uid = auth.uid
     #   user.email = auth.info.email
     #   user.password = Devise.friendly_token[0,20]
   #   end
 # end
  def self.from_omniauth(auth)
  if user = User.find_by_email(auth.info.email)  # search your db for a user with email coming from fb
    return user  #returns the user so you can sign him/her in
  else
    user = User.create(provider: auth.provider,    # Create a new user if a user with same email not present
                       uid: auth.uid,
                       email: auth.info.email,
                       password: Devise.friendly_token[0,20],
      nickname: auth.info.name, status: 'offline',exp:0, lvl:1, exptolvl:20)
    flash[:notice] = "User successfully created"
    return user

  end
end
  def online?
    scope :online, lambda{ where("updated_at > ?", 10.minutes.ago) }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @users = User.all
    respond_with(@users)
  end

  def show
    respond_with(@user)
  end

  def new
    @user = User.new
    respond_with(@user)
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.save
    respond_with(@user)
  end

  def update
    @user.update(user_params2)
    respond_with(@user)
  end

  def destroy
    @user.destroy
    respond_with(@user)
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

   def user_params
      params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :exp, :exptolvl, :lvl, :status)
   end
  
   def user_params2
     params.require(:user).permit(:password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    
    <tr>
      <th>Nickname</th>
      <th>Email</th>
      <th>Level</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    
    <% @users.each do |user| %>
      <tr>       
        <td><%=user.nickname%></td>
        <td><%=user.email%></td>
        <td><%=user.lvl%></td>
        <td><%= link_to 'Show', user %></td>
        <%if ((current_user.id == user.id) || (current_user.admin?))%>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%elsif (current_user.id != user.id)%>
        <td><%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nickname:</strong>
  <%= @user.nickname %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user.status %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<p>
  <strong>Exp:</strong>
  <%= @user.exp %>
</p>

<p>
  <strong>Exptolvl:</strong>
  <%= @user.exptolvl %>
</p>

<p>
  <strong>Lvl:</strong>
  <%= @user.lvl %>
</p>
<h2><%=@user.nickname%>'s Friends</h2>
<ul>
  <% for friendship in @user.friendships %>
  <li>
    <%= h link_to friendship.friend.nickname, friendship.friend %>
    (<%= link_to "remove", friendship, :method => :delete %>)
  </li>
  <% end %>
  <h2>Users Who Have Befriended <%=@user.nickname%></h2>
<ul>
  <% for user in @user.inverse_friends %>
  <li><%= h link_to user.nickname, user %></li>
  <% end %>
</ul>
<%= link_to "Find Friends", users_path %> |
<%= link_to 'Edit', edit_user_registration_path %> |
<%= link_to 'Back', users_path %>